name: hello_tts_dart
description: Dart implementation supporting both Edge TTS and Google TTS
version: 1.0.0

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  http: ^0.13.5
  args: ^2.4.0
  path: ^1.8.3
  web_socket_channel: ^2.4.0
  uuid: ">=3.0.7 <5.0.0"
  logging: ^1.1.0

dev_dependencies:
  test: ^1.21.0
  lints: ^2.0.0

executables:
  hello_tts: main
